sudo: false

language: node_js

node_js:
  - '8'

before_script:
  - npm run build

script:
  - npm run lint
  - npm test

after_success:
  - openssl aes-256-cbc -K $encrypted_f84add72cad3_key -iv $encrypted_f84add72cad3_iv -in .travis_rsa.enc -out $HOME/.ssh/id_rsa -d
  - chmod 600 $HOME/.ssh/id_rsa
  - .bin/travis-deploy.sh
